### ISSUE TITLE
OAuth login and interacting with My Churchsuite.

### ISSUE THREAD

**Issue by nanorepublica** [ChurchSuite/churchsuite-api#21]
Hi there, 

I have been doing some experiments with the Churchsuite OAuth and had a couple of questions:

1. How might I go about getting a user to authenticate/authorise themselves over the churchsuite OAuth service, but then hit the login screen again if I direct a user to a My churchsuite page? From this I am assuming that My Churchsuite uses a different authentication mechanism? (Happy to submit a screen recording if this is unclear)
2. The use of the `X-Auth` is non standard in terms of web authentication, is there any reason the standard `Authorization` header is not supported?

Many Thanks in Advance!

**Comment by gjcourtney** [comment]
1. Not sure that I understand this - if you direct a user to a My ChurchSuite URL and they're not authenticated then they'll be redirected to the Login screen in order to log in to My.
2. The use of `X-Auth` is how our API is currently configured to work. We may look to additionally support the `Authorization` header at some point, but at the time we initially launched the API, this wasn't as wide-spread as it is today.

**Comment by darbymanning** [comment]
Hey @gjcourtney. Any chance point 2. from
above might be considered? ie. Supporting the `Authorization` header, but keeping `X-Auth` too (just for backwards compatibility). It would improve DX a lot if we could 🙏

**Comment by gjcourtney** [comment]
@nanorepublica just a note that we have now introduced support for the Authorization header: https://github.com/ChurchSuite/churchsuite-api/issues/24
