### ISSUE TITLE
Calendar JSON feed

### ISSUE THREAD

**Issue by Mat-Moo** [ChurchSuite/churchsuite-api#33]
The JSON calendar feed doesn't seem to be returning anything past the end of Jan 2025? I normally just get the full available feed, and been reported nothing on website for Feb onwards, and looking at the feed there is nothing past the end of Jan 2025. 

X.churchsuite.com/embed/calendar/json?date_start=2025-01-01 - gives me all of Jan events
X.churchsuite.com/embed/calendar/json?date_start=2025-02-01 - Blank result set

And yes I can see events in our Churchsuite instance

**Comment by Woody93** [comment]
In case it helps, same here.

**Comment by Skyrail** [comment]
Hey folks, sorry about that. That has been fixed now so you should see the correct results beyond Feb 2025.

By default we return the next 3 months of data, however without a date_end provided it would default to 3 months from 'today', rather than 3 months from the provided start date. This has now been fixed and the default end date will be relative to the date_start provided.

If you have any further issues give us a shout at support@churchsuite.com and we'll make sure it gets to the right person.
