### ISSUE TITLE
Small group json change for custom_fields

### ISSUE THREAD

**Issue by edwardsph** [ChurchSuite/churchsuite-api#7]
The example JSON for small groups in https://github.com/ChurchSuite/churchsuite-api/blob/master/modules/smallgroups.md doesn't define the structure of custom_fields however it recently changed in a way that broke integrations. The list of options was previously a string with items separated by '\n' but is now a string array. This is obviously much better but highlights the need to have the data structures documented and changes highlighted.

**Comment by jeremyscode** [comment]
Hi @edwardsph, unfortunately this is a case of old data formats not being properly dealt with. We used to store the data `\n` separated, which as you say isn't great, and switched to storing it as a string array. We are aware that our API documentation isn't great and needs a lot of TLC and this is on our radar. Our first priority though is to make sure that our API endpoints are consistent and secure. I will add a quick description of how our custom fields work with the API, this will likely be outside of the rest of the API docs since it's a fairly global concept. Thanks!
